### ISSUE TITLE
[Question] Disabling lava lakes

### ISSUE THREAD

**Issue by Nekkok** [orlouge/structure-palettes#3]
Hi! From what I read, this should also work for the lava lake feature, am I right? If so, could you explain me how to do it? Starting on the name of the same feature, which I have no clue what it is... And I would replace the lava blocks with the default terrain block for each biome and the same with the stone blocks that surround the lakes. Maybe this is too much, but with a little info I could try to experiment with it. Thank you n_n

**Comment by orlouge** [comment]
You need the "configured feature" identifier, which is minecraft:lake_lava for lava lakes, so it would be something like:

    no_lava_lake => minecraft:lake_lava
    no_lava_lake:
    minecraft:lava -> minecraft:grass_block
    minecraft:stone -> minecraft:grass_block

The problem is that lake_lava is used for both surface and underground lava pools, so replacing the lava with grass would also generate grass underground. Moreover, replacing stone with grass would generate grass on top of grass, which would look ugly until the bottom grass is converted to dirt.
It's just not the right mod for what you're trying to do.

**Comment by Nekkok** [comment]
Well, thank you for telling me! I hate those pesky ones generating on the surface. I still really like your mod, gives lots of personalization <3
